services:
  # --- BANCO DE DADOS PRINCIPAL (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: scv_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password_secure_123
      POSTGRES_DB: saude_ciclo_vida_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scv_network

  # --- INTERFACE DE ADMINISTRAÇÃO (PGAdmin) ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: scv_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@saudeciclo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - scv_network

volumes:
  pgdata:

networks:
  scv_network:
    driver: bridge