version: '3.8'

services:
  db:
    image: postgres:15
    container_name: saude_db_container
    restart: always
    ports:
      - "5433:5432" # <--- MUDANÇA TÁTICA AQUI (Porta Externa 5433)
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: saude_ciclo_vida
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: